name: CI - Step 2 - Build and release

on:
  push:
    tags:
      - 'v*'  # This will trigger on any tag that starts with 'v'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Verify Maven version
        run: mvn -version

      - name: Clean Maven repository
        run: mvn clean

      - name: Build with Maven
        run: mvn clean install -DskipTests -X

      - name: Extract tag name
        id: extract_tag_name
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_tag_name.outputs.tag_name }}
          release_name: Release ${{ steps.extract_tag_name.outputs.tag_name }}
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/script_control_panel-1.0.jar
          asset_name: script_control_panel-1.0.jar
          asset_content_type: application/java-archive
